<?php
/** Idempotent storefront and information page seed. */
defined( 'WP_CLI' ) || exit( 1 );

function kuka_content_page( string $slug, string $title, string $content ): int {
	$existing = get_page_by_path( $slug );
	$data = array( 'post_type' => 'page', 'post_status' => 'publish', 'post_name' => $slug, 'post_title' => $title, 'post_content' => $content );
	if ( $existing ) { $data['ID'] = $existing->ID; }
	$id = $existing ? wp_update_post( $data, true ) : wp_insert_post( $data, true );
	if ( is_wp_error( $id ) ) { WP_CLI::error( $id->get_error_message() ); }
	return (int) $id;
}

$legal_prefix = '[kuka_legal_warning]<h2>Satıcı / veri sorumlusu bilgileri</h2>[kuka_company_details]';
$pages = array(
	'hakkimizda' => array( 'Hakkımızda', '<p>Kuka Island, Akdeniz kıyılarının açıklığını sade formlar ve birlikte yaşaması kolay renklerle yorumlayan bir mayo markasıdır. Bu metin, gerçek kuruluş hikâyesi müşteriden gelene kadar kullanılan özgün ve geçici marka anlatısıdır.</p><h2>Form özgürlüğü</h2><p>Bikini üstü ve altını tek bir takım kalıbına bağlamıyoruz. Farklı beden, renk ve kesimleri bağımsız seçme özgürlüğü; görünüş kadar rahatlığı da kişisel kılar.</p><h2>Ada ritmi</h2><p>Amacımız gösterişli ayrıntılar yerine hareketi izleyen çizgiler, dengeli kapama ve tekrar giyilebilen parçalar sunmak. Üretim yeri, kuruluş yılı veya sertifika iddiası; doğrulanmış müşteri verisi gelmeden yayımlanmaz.</p>' ),
	'iletisim' => array( 'İletişim', '<p>Sipariş, ürün ve beden soruları için aşağıdaki güncel kanalları kullanabilirsiniz.</p>[kuka_contact_details]<h2>İletişim formu</h2><p class="kuka-service-disabled"><strong>Form şu anda devre dışıdır.</strong> Mesaj gönderim altyapısı bağlanana kadar e-posta, telefon, WhatsApp veya Instagram kanalını kullanın.</p>' ),
	'sik-sorulan-sorular' => array( 'Sık Sorulan Sorular', '<h2>Beden ve kalıp</h2><h3>Bedenimi nasıl seçerim?</h3><p>Göğüs, göğüs altı, bel ve kalça ölçünüzü santimetre olarak alın; Beden Rehberi tablosu ile ürünün kalıp notunu birlikte değerlendirin.</p><h3>İki beden arasında kalırsam ne yapmalıyım?</h3><p>Üründeki kalıp önerisi önceliklidir. Standart pilot kalıplarda daha rahat kullanım için büyük beden değerlendirilebilir.</p><h3>Üst ve altı farklı beden alabilir miyim?</h3><p>Evet. Bikini üstleri ve altları ayrı ürünlerdir; beden ve renklerini bağımsız seçebilirsiniz.</p><h3>Beden rehberi nerede?</h3><p>Her ürünün beden bağlantısından veya <a href="/beden-rehberi/">Beden Rehberi</a> sayfasından açılır.</p><h2>Ürün ve kumaş</h2><h3>Kumaş içeriğini nerede görürüm?</h3><p>Her ürün sayfasındaki Malzeme bölümünde ürüne özgü oranlar bulunur.</p><h3>Bakım nasıl yapılır?</h3><p>Ürünün bakım notunu izleyin; genel olarak soğuk suda elde yıkayın, sıkmayın ve gölgede düz kurutun.</p><h3>Klor ve güneş kremi ürünü etkiler mi?</h3><p>Klorlu veya tuzlu sudan sonra durulayın. Güneş kremi ve yağla uzun temas renk ve elastikiyeti etkileyebilir.</p><h3>Astar veya dolgu var mı?</h3><p>Astar ve çıkarılabilir/sabit dolgu bilgisi ürün açıklamasında belirtilir; ürünler arasında farklılık gösterebilir.</p><h2>Kargo</h2><p>Standart kargo ücreti [kuka_value name="flat_shipping_fee"], ücretsiz kargo eşiği [kuka_value name="free_shipping_threshold"] değeridir. Taşıyıcı [kuka_value name="shipping_carrier"], tahmini süre [kuka_value name="delivery_time"] olarak panelden güncellenir. Kargoya verildiğinde takip bilgisi paylaşılır.</p><h2>İade ve değişim</h2><p>Talebinizi teslimattan sonra [kuka_value name="return_period_days"] gün içinde destek ekibine iletin. İade gönderim masrafı için güncel karar: [kuka_value name="return_shipping_responsibility"].</p><p>[kuka_hygiene_policy]</p><h2>Ödeme</h2><p>Checkout ekranında gösterilen kart yöntemleri kullanılır. Taksit seçeneği banka ve iyzico koşullarına göre ödeme sırasında görünür. Kart verisi Kuka Island sunucusunda saklanmaz; ödeme kuruluşunun güvenli altyapısında işlenir.</p><h2>Sipariş</h2><p>Sipariş durumunu sipariş numarası ve e-posta ile <a href="/siparis-takibi/">Sipariş Takibi</a> sayfasından sorgulayabilirsiniz. Hazırlık başlamadan önce iptal talebi destek ekibine iletilebilir; tamamlanmış faturaya sipariş hesabınızdan erişebilirsiniz.</p>' ),
	'kargo-teslimat' => array( 'Kargo ve Teslimat', '<h2>Hazırlık ve teslimat</h2><p>Siparişler ödeme onayından sonra hazırlanır. Tahmini teslimat süresi [kuka_value name="delivery_time"], taşıyıcı [kuka_value name="shipping_carrier"] olarak panelde tutulur. Hafta sonu, resmî tatil, yoğun dönem ve teslimat bölgesi süreyi etkileyebilir.</p><h2>Ücret ve ücretsiz kargo</h2><p>Standart gönderim ücreti [kuka_value name="flat_shipping_fee"], ücretsiz gönderim eşiği [kuka_value name="free_shipping_threshold"] değeridir. Checkout ekranındaki sipariş özeti uygulanacak son tutarı gösterir.</p><h2>Takip</h2><p>Kargo takip numarası yönetici tarafından siparişe girildiğinde e-posta ile paylaşılır ve Sipariş Takibi ekranında kullanılabilir.</p><h2>Yanlış adres</h2><p>Kargoya verilmeden önce destek ekibine ulaşın. Gönderim başladıktan sonra adres değişikliği taşıyıcının kabulüne bağlıdır; teslim edilemeyen paketin yeniden gönderim bedeli doğabilir.</p><h2>Hasarlı teslimat</h2><p>Pakette belirgin hasar varsa mümkünse teslimat görevlisi yanında kayıt tutun; paket ve ürün fotoğraflarıyla sipariş numarasını gecikmeden destek ekibine iletin.</p>' ),
	'iade-degisim' => array( 'İade ve Değişim Koşulları', $legal_prefix . '<h2>Cayma ve talep süreci</h2><p>Cayma veya değişim talebinizi ürünü teslim aldığınız tarihten itibaren [kuka_value name="return_period_days"] gün içinde, sipariş numaranız ve kullandığınız e-posta adresiyle destek kanalına iletin. Ekip iade adresini ve gönderim adımlarını yazılı olarak paylaşır.</p><h2>İade kargo ücreti</h2><p>Güncel operasyon kararı: [kuka_value name="return_shipping_responsibility"]. Bu yer tutucu müşteri tarafından kesinleştirilmeden metin yürürlüğe alınmamalıdır.</p><h2>Değişim akışı</h2><p>İstenen beden veya ürün stokta ise değişim kaydı açılır. Stok yoksa iade seçeneği sunulur. Yeni ürün, dönen ürünün kontrolü tamamlandıktan sonra gönderilir.</p><h2>Hijyen koruması ve istisna</h2><p>[kuka_hygiene_policy]</p><h2>Ürünün durumu</h2><p>Ürün; denenmenin gerektirdiği ölçüyü aşmadan, yıkanmadan, etiketi ve varsa koruyucu unsuru zarar görmeden gönderilmelidir. Ayıplı ürün bildirimleri cayma sürecinden ayrı değerlendirilir.</p>' ),
	'gizlilik-politikasi' => array( 'Gizlilik Politikası', $legal_prefix . '<h2>Yaklaşım ve kapsam</h2><p>Kişisel verileri belirli, açık ve meşru amaçlarla; hizmet için gerekli olanla sınırlı biçimde işleriz. Ayrıntılı veri kategorileri, hukuki sebepler ve haklar KVKK Aydınlatma Metni’nde açıklanır.</p><h2>Güvenlik tedbirleri</h2><p>Yönetim erişimleri görevle sınırlandırılır, güçlü ve ayrı parolalar kullanılır, yazılım güncellemeleri kontrollü yapılır, trafik HTTPS ile korunur ve yedekler erişim kontrollü alanlarda tutulur. Ödeme kartı verileri Kuka Island sunucusunda saklanmaz.</p><h2>Üçüncü taraf hizmetler</h2><p>Siparişin tamamlanması için iyzico, kargo firması, SMTP/e-posta servisi, barındırma sağlayıcısı ve varsa e-Arşiv entegratörü kendi rolleri kapsamında veri işleyebilir. Bu taraflarla yalnız gerekli veri paylaşılır.</p><h2>Çerezler ve iletişim tercihleri</h2><p>Çerez ayrıntıları Çerez Politikası’nda açıklanır. Bülten iletişimi yalnız onay verilirse başlar ve onay geri alınabilir; mevcut bülten formu entegrasyon kurulana kadar devre dışıdır.</p><h2>Başvuru</h2><p>Gizlilik talebinizi [kuka_value name="email"] adresine veya yukarıdaki şirket adresine iletebilirsiniz. Kimlik doğrulamak için taleple orantılı ek bilgi istenebilir.</p>' ),
	'cerez-politikasi' => array( 'Çerez Politikası', $legal_prefix . '<h2>Mevcut çerez kullanımı</h2><p>Bu test yayınında Google Analytics, Meta Pixel veya başka bir analitik/pazarlama takip aracı kurulu değildir. Zorunlu olmayan çerezler varsayılan olarak kapalıdır ve böyle bir araç eklenmeden önce ayrı onay mekanizması kurulacaktır.</p><h2>Zorunlu çerezler</h2><table><thead><tr><th>Çerez grubu</th><th>Amaç</th><th>Saklama</th></tr></thead><tbody><tr><td>WooCommerce sepet çerezleri</td><td>Sepette ürün bulunup bulunmadığını ve sepet değişikliklerini hatırlamak</td><td>Oturum süresince</td></tr><tr><td>WooCommerce müşteri oturumu</td><td>Ziyaretçiye sepet içeriğini bağlamak</td><td>Varsayılan olarak 2 gün</td></tr><tr><td>WordPress giriş çerezleri</td><td>Hesaba giriş yapan kullanıcıyı doğrulamak</td><td>Oturum süresince; “beni hatırla” seçilirse daha uzun</td></tr></tbody></table><h2>İşlevsel çerezler</h2><p>Kullanıcının açık tercihini hatırlayan işlevsel çerezler, ilgili özellik devreye alınırsa kullanılır. Mevcut test yayınında ayrı bir kişiselleştirme çerezi bulunmamaktadır.</p><h2>Analitik ve pazarlama</h2><p>Mevcut kurulumda analitik veya pazarlama çerezi yoktur. Gelecekte eklenirse sağlayıcı, amaç, süre ve aktarım bilgisi bu tabloda yayımlanacak; çerez kullanıcı onayından önce çalışmayacaktır.</p><h2>Tarayıcıdan yönetim</h2><p>Çerezleri tarayıcı ayarlarından görebilir, silebilir veya engelleyebilirsiniz. Zorunlu çerezlerin engellenmesi sepet, checkout ve hesap girişinin çalışmamasına yol açabilir.</p>' ),
	'kvkk-aydinlatma-metni' => array( 'KVKK Aydınlatma Metni', $legal_prefix . '<h2>İşlenen kişisel veriler</h2><p>Ad soyad, e-posta, telefon, teslimat ve fatura adresi, sipariş geçmişi; kurumsal fatura seçilirse şirket unvanı, VKN ve vergi dairesi; bülten onayı ve zorunlu/tercihe bağlı çerez verileri işlenebilir. Bu listede sitede toplanmayan veri kategorisi bulunmaz.</p><h2>İşleme amaçları</h2><p>Sipariş ve üyelik sözleşmesini kurmak ve yürütmek, ödemeyi doğrulamak, ürünü teslim etmek, fatura ve satış sonrası destek sağlamak, dolandırıcılık ve sistem güvenliği kontrollerini yapmak, yasal yükümlülükleri yerine getirmek ve yalnız onay varsa bülten göndermek.</p><h2>Hukuki sebepler</h2><p>Veriler; sözleşmenin kurulması veya ifası, hukuki yükümlülük, bir hakkın tesisi/kullanılması/korunması ve temel haklara zarar vermemek kaydıyla meşru menfaat sebeplerine dayanır. Bülten gibi izinli iletişim faaliyeti açık onay/izin bulunduğunda yürütülür.</p><h2>Aktarım</h2><p>Gerekli veriler; ödeme işlemi için iyzico’ya, teslimat için [kuka_value name="shipping_carrier"] tarafına, bildirim için SMTP/e-posta servisine, teknik barındırma için hosting sağlayıcısına ve kurulursa yasal fatura için e-Arşiv entegratörüne aktarılabilir. Yetkili kamu kurumlarına yalnız hukuki zorunluluk kapsamında aktarım yapılır.</p><h2>Saklama süreleri</h2><p>Sipariş ve fatura kayıtları ilgili mali/ticari mevzuatta zorunlu süre boyunca; hesap verileri hesap açık kaldığı ve uyuşmazlık zamanaşımı gerektirdiği sürece; destek kayıtları talep sonuçlanıp savunma süresi dolana kadar; bülten onayı geri alınana kadar; çerezler Çerez Politikası’ndaki süreler boyunca saklanır. Süre bitince veri silinir, yok edilir veya anonimleştirilir.</p><h2>İlgili kişi hakları ve başvuru</h2><p>Verinizin işlenip işlenmediğini öğrenme, bilgi isteme, amacına uygun kullanımı öğrenme, aktarılan tarafları bilme, düzeltme, silme/yok etme isteme, otomatik analiz sonucuna itiraz etme ve kanuna aykırılık nedeniyle zarar doğarsa giderim talep etme haklarınızı kullanabilirsiniz. Başvurunuzu [kuka_value name="email"] adresine veya yukarıdaki posta adresine, kimliğinizi doğrulayacak bilgilerle iletin.</p>' ),
	'kullanim-kosullari' => array( 'Kullanım Koşulları', '[kuka_legal_warning]<h2>Kapsam</h2><p>Site içeriği, hesap güvenliği, fikri mülkiyet ve hizmetin dürüst kullanımına ilişkin nihai koşullar şirket ve hukuk onayı sonrasında yürürlüğe alınacaktır.</p>' ),
	'on-bilgilendirme-formu' => array( 'Ön Bilgilendirme Formu', $legal_prefix . '<h2>Ürünün temel nitelikleri ve toplam fiyat</h2><p>Seçilen ürünün adı, renk/beden varyasyonu, adet, vergiler dahil birim ve toplam fiyatı checkout sipariş özetinde sipariş verilmeden önce gösterilir. Bu sayfadaki genel metin, siparişe özgü özeti değiştirmez.</p><h2>Kargo, ödeme ve teslimat</h2><p>Standart kargo [kuka_value name="flat_shipping_fee"], ücretsiz kargo eşiği [kuka_value name="free_shipping_threshold"] değeridir; masraf sipariş özetinde alıcıya gösterilir. Taşıyıcı [kuka_value name="shipping_carrier"], tahmini teslimat [kuka_value name="delivery_time"] olarak yönetilir. Ödeme yöntemi ve varsa taksit bilgisi iyzico ekranında seçimden önce görünür.</p><h2>Cayma hakkı ve bildirim</h2><p>Alıcı, ürünü teslim aldıktan sonra [kuka_value name="return_period_days"] gün içinde gerekçe göstermeden cayma bildirimini sipariş numarasıyla [kuka_value name="email"] adresine iletebilir. İade adresi ve taşıma yöntemi cevapta paylaşılır. İade kargo sorumluluğu: [kuka_value name="return_shipping_responsibility"].</p><h2>İstisna</h2><p>[kuka_hygiene_policy]</p><h2>Şikâyet ve uyuşmazlık</h2><p>Destek başvurusu öncelikle satıcıya iletilebilir. Çözüm sağlanamazsa tüketici, yürürlükteki parasal sınırlara göre yerleşim yerindeki veya işlemin yapıldığı yerdeki Tüketici Hakem Heyetine ya da Tüketici Mahkemesine başvurabilir.</p>' ),
	'mesafeli-satis-sozlesmesi' => array( 'Mesafeli Satış Sözleşmesi', $legal_prefix . '<h2>Alıcı</h2><p>Alıcının adı, iletişim ve teslimat/fatura bilgileri sipariş sırasında verdiği bilgilerdir ve sipariş kaydının parçasıdır.</p><h2>Sözleşmenin konusu</h2><p>Bu sözleşme, alıcının elektronik ortamda sipariş ettiği mayo, bikini veya diğer ürünlerin satışı ve teslimi ile tarafların hak ve yükümlülüklerini düzenler. Ürün adı, renk, beden, adet, vergiler dahil fiyat, indirim, kargo ve genel toplam checkout sipariş özetinde yer alır.</p><h2>Ödeme</h2><p>Ödeme, checkout ekranında sunulan iyzico yöntemlerinden seçilir. Sipariş, ödeme doğrulamasıyla işleme alınır; kart bilgileri satıcı sunucusunda saklanmaz.</p><h2>Teslimat</h2><p>Teslimat [kuka_value name="shipping_carrier"] aracılığıyla, checkout sırasında belirtilen adrese yapılır. Tahmini süre [kuka_value name="delivery_time"] olup siparişin niteliği veya mücbir sebep nedeniyle değişebilir; mevzuattaki azami süre saklıdır.</p><h2>Cayma hakkı</h2><p>Alıcı, teslimden itibaren [kuka_value name="return_period_days"] gün içinde [kuka_value name="email"] adresine açık bir bildirim göndererek cayabilir. Ürün, bildirimi izleyen yasal süre içinde talimatta bildirilen adrese gönderilir. İade kargo sorumluluğu: [kuka_value name="return_shipping_responsibility"].</p><h2>Cayma hakkının kullanılamayabileceği hâl</h2><p>[kuka_hygiene_policy]</p><h2>Uyuşmazlık çözümü</h2><p>Uyuşmazlıkta yürürlükteki parasal sınırlara göre alıcının yerleşim yerindeki veya işlemin yapıldığı yerdeki Tüketici Hakem Heyeti ya da Tüketici Mahkemesi yetkilidir.</p><h2>Geçerlilik</h2><p>Alıcı, Ön Bilgilendirme Formu ve bu sözleşmeyi checkout onay kutularıyla kabul ettiğinde sözleşme sipariş kaydıyla birlikte elektronik ortamda kurulur. Emredici tüketici hükümleri öncelikle uygulanır.</p>' ),
	'acik-riza-metni' => array( 'Açık Rıza Metni', '[kuka_legal_warning]<h2>İsteğe bağlı işlemler</h2><p>Mevcut sipariş akışı için ayrı açık rıza şart koşulmaz. Gelecekte açık rıza gerektiren bir faaliyet eklenirse amacı, veri kategorisi ve geri alma yöntemi bu metinde ayrı olarak açıklanacaktır.</p>' ),
	'ticari-elektronik-ileti-onayi' => array( 'Ticari Elektronik İleti Onayı', '[kuka_legal_warning]<h2>İletişim tercihi</h2><p>Bülten altyapısı şu anda devre dışıdır. Etkinleştirildiğinde e-posta ile kampanya/ürün iletişimi yalnız ayrı onayla gönderilecek; her iletide ret yolu sunulacaktır.</p>' ),
	'beden-rehberi' => array( 'Beden Rehberi', '<p>Tüm vücut ölçüleri santimetredir (cm). Mezurayı bedeni sıkıştırmadan ve yere paralel tutun.</p><h2>Nasıl ölçülür?</h2><ul><li><strong>Göğüs:</strong> Göğsün en dolgun noktasından yatay ölçün.</li><li><strong>Göğüs altı:</strong> Göğsün hemen altından, mezura düz kalacak biçimde ölçün.</li><li><strong>Bel:</strong> Doğal bel çizgisinin en dar noktasını ölçün.</li><li><strong>Kalça:</strong> Kalçanın en geniş noktasından yatay ölçün.</li></ul><p>İki beden arasında kalırsanız ürün sayfasındaki kalıp notunu değerlendirin. Bikini üstü ve altı ayrı satıldığı için farklı bedenler seçebilirsiniz.</p>[kuka_size_guide]' ),
	'siparis-takibi' => array( 'Sipariş Takibi', '<p>Sipariş numaranızı ve siparişte kullandığınız e-posta adresini girin. Yönetici kargo takip numarasını siparişe eklediğinde gönderi bilgisi sipariş detayında görünür.</p>[woocommerce_order_tracking]' ),
	'tipografi-testi' => array( 'Tipografi Testi', '<section class="kuka-type-test" aria-label="Türkçe diakritik başlık testi"><h2>Bikini Üstü</h2><h2>Yüksek Bel Bikini Altı</h2><h2>Straplez Mayo</h2><h2>İpli / Yan Bağlamalı</h2></section>' ),
);
foreach ( $pages as $slug => $page ) { kuka_content_page( $slug, $page[0], $page[1] ); }
$home_id = kuka_content_page( 'ana-sayfa', 'Ana Sayfa', '' );
update_option( 'show_on_front', 'page' ); update_option( 'page_on_front', $home_id );

$attachment_id = static function ( string $source ): int {
	$ids = get_posts( array( 'post_type' => 'attachment', 'post_status' => 'inherit', 'posts_per_page' => 1, 'meta_key' => '_kuka_seed_source', 'meta_value' => $source, 'fields' => 'ids' ) );
	return $ids ? (int) $ids[0] : 0;
};
if ( class_exists( 'Kuka_Island_Core_Site_Appearance' ) ) {
	$current = Kuka_Island_Core_Site_Appearance::get();
	$current['hero']['desktop_image_id'] = $attachment_id( 'hero-aegean-black.jpg' );
	$current['hero']['mobile_image_id'] = $attachment_id( 'hero-aegean-black-mobile.jpg' );
	$current['home']['editorial_image_id'] = $attachment_id( 'cobalt-set.jpg' );
	$current['brand']['social_links'] = Kuka_Island_Core_Site_Appearance::defaults()['brand']['social_links'];
	$current['navigation']['help'] = Kuka_Island_Core_Site_Appearance::defaults()['navigation']['help'];
	$current['footer']['help_links'] = Kuka_Island_Core_Site_Appearance::defaults()['footer']['help_links'];
	$current['footer']['legal_links'] = Kuka_Island_Core_Site_Appearance::defaults()['footer']['legal_links'];
	update_option( Kuka_Island_Core_Site_Appearance::OPTION_NAME, $current, false );
	Kuka_Island_Core_Site_Appearance::sync_free_shipping_threshold();
}
flush_rewrite_rules( false );
WP_CLI::success( sprintf( '%d içerik sayfası ve Site Appearance görselleri hazır.', count( $pages ) + 1 ) );
